name: "Nuclei Action"
description: "Nuclei is a fast and customisable vulnerability scanner based on simple YAML based DSL"

inputs:
  target:
    description: "Target to run nuclei scan"
    required: true
  templates:
    description: "Templates input file/files to check across hosts"
    required: false
  output:
    description: "File to save output result"
    required: false
    default: "nuclei.log"
  sarif-export:
    description: "Export output in sarif format"
    required: false
    default: "nuclei.sarif"
  include-rr:
    description: "Write requests/responses for matches in JSON output"
    required: false
    default: false
  nuclei-ignore:
    description: "define templates that will be blocked from execution"
    required: false
  user-agent:
    description: "Set a User-Agent header"
    required: false
  github-report:
    description: "Active Nuclei Reporting Module for Github"
    required: false
    default: false
  github-token:
    description: "Github token for create issues"
    required: false
    
runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/nuclei ] && GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@sarif-integration
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        [ ! -z ${{ inputs.nuclei-ignore }} ] && cp ${{ inputs.nuclei-ignore }} /nuclei-templates/.nuclei-ignore
        [ ! -z "${{ inputs.user-agent }}" ] && echo 'useragent=-H "User-Agent: ${{ inputs.user-agent }}"' >> $GITHUB_ENV
        ${{ inputs.include-rr }} && echo "includerr=-irr" >> $GITHUB_ENV

        ${{ inputs.github-token }} \
        && touch ~/nuclei-report-config.yaml \
        && echo -e "github:" >> ~/nuclei-report-config.yaml \
        && echo -e "  username: \"$GITHUB_ACTOR\"" >> ~/nuclei-report-config.yaml \
        && echo -e "  owner: \"${GITHUB_REPOSITORY%%/*}\"" >> ~/nuclei-report-config.yaml \
        && echo -e "  token: \"${{ inputs.report-token }}\"" >> ~/nuclei-report-config.yaml \
        && echo -e "  project-name: \"${GITHUB_REPOSITORY#*/}\"" >> ~/nuclei-report-config.yaml \
        && echo -e "  issue-label: \"Nuclei Reporting\"" >> ~/nuclei-report-config.yaml \
        && echo "reportconfig=-rc ~/nuclei-report-config.yaml" >> $GITHUB_ENV
        
        nuclei \
          -update-templates -silent \
          -update-directory ./nuclei-templates
      shell: bash

    - run: |
        nuclei -silent \
          -target ${{ inputs.target }} \
          -t ./nuclei-templates/${{ inputs.templates }} \
          ${{ env.useragent }} \
          -o ${{ inputs.output }} \
          ${{ env.reportconfig }} \
          -sf ${{ inputs.sarif-export }} \
          ${{ env.includerr }}
      shell: bash
